#!/bin/sh
# For comparision you have to use square brackets.
echo "true yields 0, false yields 1"
x="005"
[ "$x" = "005" ]
echo "Are strings 005 and 005 equal? $?"
[ "$x" = "5" ]
echo "Are strings 005 and 5 equal? $?"
[ $x -eq 005 ]
echo "Are integers 005 and 005 equal? $?"
[ $x -eq 5 ]
echo "Are integers 005 and 5 equal? $?"
